version: "3"

networks:
  # Using traefik
  proxy:
    external: true

services:
  wordpress:
    container_name: "${COMPOSE_PROJECT_NAME}-wordpress"
    image: "wordpress:php${PHP_VERSION}"
    restart: "${WORDPRESS_RESTART}"
    volumes:
      - ${WORDPRESS_PATH}:/var/www/html
    # Using traefik
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}-wordpress.entrypoints=${WORDPRESS_ENTRYPOINTS}
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}-wordpress.rule=Host(${WORDPRESS_DOMAINS})
    networks:
      - proxy
    expose:
      - 80
      - 443
