version: "3"

networks:
  # Using traefik
  proxy:
    external: true

services:
  wordpress:
    container_name: "${COMPOSE_PROJECT_NAME}-wordpress"
    image: "wordpress:php${PHP_VERSION:-8.2}"
    restart: "${WORDPRESS_RESTART:-no}"
    volumes:
      - ${WORDPRESS_PATH:-./public_html}:/var/www/html
      - ./php.ini:/usr/local/etc/php/conf.d/php.ini
    # Using traefik
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}-wordpress.entrypoints=${WORDPRESS_ENTRYPOINTS:-web}
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}-wordpress.rule=Host(${WORDPRESS_DOMAINS:-`wordpress.localhost`})
    networks:
      - proxy
    expose:
      - 80
      - 443
